### ISSUE TITLE
Support for new single / multi-hop reasoning methods on KG.

### ISSUE THREAD

**Issue by nadgeri14** [google-research/smore#2]
Hi Team, 

Congratulations on the exciting work !! 
Is it possible to merge new single / multi-hop reasoning methods on KG into SMORE ? 

Best 
Abhishek

**Comment by hyren** [comment]
Thanks for your interest! Yes, feel free to create a pull request and please check [contributing](https://github.com/google-research/smore/blob/main/CONTRIBUTING.md) page for more information.
