### ISSUE TITLE
How to get the data including train_bidir.bin? 

### ISSUE THREAD

**Issue by leiloong** [google-research/smore#6]
Hi Contributors, congratulations on your exciting work.

A small problem that, I fail to find out how to get the data for training. After I download the complex query data by "wget http://data.neuralnoise.com/cqd-data.tgz" from "https://github.com/uclnlp/cqd", the "train_bidir.bin" file is still missing?
How could I get theses files? 

Best Regards, 
Lei

**Comment by hyren** [comment]
Hi, please check the box/beta/vec scripts in the latest master branch. It allows for automatic downloading of the data. Currently it supports downloading of FB15k, FB15k-237, NELL and FB400k. We are working on the two large datasets OGB-wikikg2 and Freebase. Let me know if you have any questions.

**Comment by susierao** [comment]
Dear developers, Thank you very much for the great contributions. 
Could you elaborate on how to create a train_bidir.bin file from a KG? We wanted to train embeddings on our own datasets. Or are there any other formats like pkl, csv supported in the current framework? 
Cheers, Susie
